In [2]:
import numpy as np

### creating numpy array 

In [2]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [3]:
# numpy chỉ cho phép 1 kiểu dữ liệu trong 1 array, nếu có nhiều kiểu dữ liệu thì nó sẽ convert thành cùng 1 kiểu dữ liệu 
np.array([1.5,2,3,4])

array([1.5, 2. , 3. , 4. ])

In [4]:
np.array([1.5,2,3,4], dtype ='float32') #convert mảng thành kiểu float32

array([1.5, 2. , 3. , 4. ], dtype=float32)

In [7]:
# có thể gán mảng cho 1 biến bất kỳ 
a1 = np.array([1.5,2,3,4])

### type 

In [8]:
type(a1) #kiểm tra kiểu dữ liệu 

numpy.ndarray

### shape

In [11]:
a2 = np.array([[1,2,4],[3,5,6]])
a2.shape #return mảng xem có bao nhiêu cột và bao nhiêu dòng

(2, 3)

### ndim

In [12]:
a2.ndim #số chiều của mảng

2

### dtype 

In [13]:
a1.dtype #kiểu dữ liệu 

dtype('float64')

### size 

In [14]:
a2.size #kiểm tra xem có bao nhiêu phần tử 

6

# Tạo numpy array sử dụng các hàm có sẵn 

## zeros, ones, full, arange, linspace

### zeros

In [16]:
np.zeros([2,4]) #return về 1 mảng với giá tị là 0 

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [17]:
np.zeros([2,4],dtype= int)

array([[0, 0, 0, 0],
       [0, 0, 0, 0]])

### ones

In [18]:
np.ones([3,4]) # Trả về 1 mảng với giá trị là 1 

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

### arange([start, ] stop[, step,], dtype = None)

In [19]:
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

### full(shape, fill_value, dtype=None, order='C', *, like=None)

In [20]:
np.full((3,5), 6.9)

array([[6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9],
       [6.9, 6.9, 6.9, 6.9, 6.9]])

### linspace 
    np.linspace(
    start,
    stop,
    num=50,
    endpoint=True,
    retstep=False,
    dtype=None,
    ax is=0,
)

In [22]:
np.linspace(0,1, 5) # hàm để tạo mảng với các phần tử cách đều nhau , ở đây là tạo 1 mảng vs 5 phần tử cách đều từ 0 đến 1 

array([0.  , 0.25, 0.5 , 0.75, 1.  ])

### random ( size ) 

In [29]:
np.random.random((4,4)) # trả về một mảng các số ngẫu nhiên với giá trị nằm trong khoảng từ 0 đến 1.

array([[0.0202184 , 0.83261985, 0.77815675, 0.87001215],
       [0.97861834, 0.79915856, 0.46147936, 0.78052918],
       [0.11827443, 0.63992102, 0.14335329, 0.94466892],
       [0.52184832, 0.41466194, 0.26455561, 0.77423369]])

#### seed 

In [28]:
# Để tạo ra các số ngẫu nhiên giống nhau giữa các lần chạy ta dùng seed 
np.random.seed(0)
np.random.random((4,4))

array([[0.5488135 , 0.71518937, 0.60276338, 0.54488318],
       [0.4236548 , 0.64589411, 0.43758721, 0.891773  ],
       [0.96366276, 0.38344152, 0.79172504, 0.52889492],
       [0.56804456, 0.92559664, 0.07103606, 0.0871293 ]])

#### normal ( giá trị trung bình, độ lệch chuẩn, size ) 
tạo ra các số ngẫu nhiên theo phân phối chuẩn (phân phối Gaussian) 

In [30]:
np.random.normal(0,1,10) 

array([ 2.26975462, -1.45436567,  0.04575852, -0.18718385,  1.53277921,
        1.46935877,  0.15494743,  0.37816252, -0.88778575, -1.98079647])

#### randint ()
randint(low, high, size = None ) 
Tạo 1 mảng với các số NGUYÊN ngẫu nhiên nằm trong khoảng từ low đến high

In [4]:
np.random.randint(0,5)

2

In [16]:
np.random.randint(0,7,(2,2))
np.random.randint(7, size = (2,2))

array([[6, 1],
       [2, 1]])

#### rand(d0, d1, ...., dn) 
rand khác với random ở chỗ ta k cần phải khai báo 1 mảng (x,y) như trong random ((x,y)) mà ta chỉ cần ran(x,y)

In [8]:
np.random.rand(4,4) 

array([[0.16086614, 0.37947282, 0.38130263, 0.75147458],
       [0.14069888, 0.60249547, 0.81601361, 0.70448917],
       [0.3861693 , 0.83873688, 0.31209096, 0.48230822],
       [0.39563133, 0.18460084, 0.44081495, 0.83719983]])

# Truy xuất phần tử trong mảng 


### đối vs mảng con 1 chiều 

In [10]:
x1 = np.random.randint(20, size = 6 ) 
x1 

array([17, 16, 11,  0, 17, 18])

In [13]:
# tiếp cận phần từ thứ bao nhiêu của mảng 
x1[4]

17

In [12]:
x1[4], x1[0], x1[-1] # Truy xuất phần tử cuôi cùng thì ta dùng [-1]

(17, 17, 18)

## đối vs mảng đa chiều 

In [17]:
x2 = np.random.randint(10, size = (3,4))
x2

array([[6, 7, 9, 7],
       [5, 6, 9, 1],
       [0, 8, 4, 1]])

In [19]:
x2[1,2] #Truy xuất phần tử hàng 2, cột 3

9

# CHIA MẢNG 


## MẢNG 1 CHIỀU
### x1[start: stop : step ], cắt từ phẩn tử thứ bao nhiêu đến phần tử thứ bao nhiêu 

In [20]:
x1

array([17, 16, 11,  0, 17, 18])

In [22]:
x1[0:2] # cắt đoạn từ phần tử 0 đến phần tử 1 (k tính phần tử 2 ) 

array([17, 16])

In [24]:
x1[::2] # Cứ 2 phần tử (step) thì cắt 1 lần 

array([17, 11, 17])

## MẢNG ĐA CHIỀU 

In [26]:
x2 

array([[6, 7, 9, 7],
       [5, 6, 9, 1],
       [0, 8, 4, 1]])

In [27]:
# cắt 2 dòng đầu, 3 cột đầu tiên 
x2[:2, :3]

array([[6, 7, 9],
       [5, 6, 9]])

In [29]:
# cắt lấy 2 cột đầu tiên và tất cả dòng
x2[:, :2]

array([[6, 7],
       [5, 6],
       [0, 8]])

# Reshaping of Arrays and Transpose 

### reshape 

In [31]:
grid = np.arange(1,10) 
grid.shape # đây là ma trận 1 chiều -> ta muốn chuyển thành ma trận dạng khác 

(9,)

In [33]:
grid.reshape((3,3)) # đã reshape về dạng 3x3 

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [34]:
x = np.array([1,2,3])

In [35]:
x.shape 

(3,)

In [39]:
grid2 = x.reshape((1,3))

In [40]:
grid2.shape

(1, 3)

### transpose ( biến hàng thành cột, cột thành hàng )  

In [42]:
x = np.array([[1,2],[3,4]])

In [43]:
x

array([[1, 2],
       [3, 4]])

In [44]:
x.T

array([[1, 3],
       [2, 4]])

# Nối mảng và tách mảng 

## Nối mảng ( array concatenation ) 



### concatenate((a1, a2, ...), axis=0, out=None, dtype=None, casting="same_kind")
axis = 0 thì nối theo hàng, axis = 1 thì nối theo cột 

In [45]:
x = np.array([1,2,3])
y = np.array([3,2,1])

In [47]:
np.concatenate((x,y))

array([1, 2, 3, 3, 2, 1])

In [49]:
grid = np.array([[1,2,3],[4,5,6 # mặc định nối theo chiều ngang
grid 

array([[1, 2, 3],
       [4, 5, 6]])

In [50]:
np.concatenate((grid, grid), axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

### vstack : nối mảng theo chiều dọc 

In [54]:
x = np.array([1,2,3])
grid = np.array([[9,8,7], [6,5,4]])

In [55]:
np.vstack((x,grid))

array([[1, 2, 3],
       [9, 8, 7],
       [6, 5, 4]])

### hstack : nối mảng theo chiều ngang 

In [63]:
y = np.array([[99],[99]])

In [64]:
np.hstack((y,grid))

array([[99,  9,  8,  7],
       [99,  6,  5,  4]])

## Chia mảng 
## split ( mảng muốn chia, [x,y]) với x,y là giới hạn mảng con muốn chia 

In [65]:
x = np.array([1,2,3,99,69,3,2,1])

In [66]:
np.split(x, [3,5])

[array([1, 2, 3]), array([99, 69]), array([3, 2, 1])]

# Broadcasting 
Broadcasting giúp thực hiện các phép toán trên các mảng có kích thước khác nhau 1 cách linh hoạt như cộng, trừ, nhân, chia mảng 

In [67]:
a = np.arange(3) 
a 

array([0, 1, 2])

In [69]:
a + 5 # broadcasting , 0+5 = 5, 1+5= 6 , 2+5 = 7

array([5, 6, 7])

In [74]:
b = np.ones((3,3))
b 

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [71]:
a + b 

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [72]:
a * b 

array([[0., 1., 2.],
       [0., 1., 2.],
       [0., 1., 2.]])

In [75]:
c = np.arange(3).reshape((3,1))
c 

array([[0],
       [1],
       [2]])

In [76]:
a + c

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

# Manipulating and Comparing Arrays 

### aggregation 

In [78]:
list = [1,2,3]

In [79]:
ll = np.array(list)

In [80]:
ll

array([1, 2, 3])

In [85]:
sum(ll) #hàm trong python

6

In [86]:
np.sum(ll) # hàm trong numpy

6

In [84]:
# create massive array 
massive_array = np.random.random(10000)
massive_array.shape

(10000,)

In [87]:
%timeit sum(massive_array)
%timeit np.sum(massive_array)

618 μs ± 16.5 μs per loop (mean ± std. dev. of 7 runs, 1,000 loops each)
5.73 μs ± 370 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)


==> hàm của numpy nhanh hơn 

In [88]:
np.mean(massive_array)

0.5005406490609139

In [89]:
np.max(massive_array)

0.9999331226589757

In [90]:
np.min(massive_array)

7.880707725482772e-05

# Standard Deviation : Độ lệch chuẩn, Variance: phương sai

#### PHƯƠNG SAI là đại lượng đo mức độ phân tán của các giá trị trong một tập dữ liệu so với giá trị trung bình của tập dữ liệu đó. Nó cho biết các giá trị trong tập dữ liệu thay đổi như thế nào so với trung bình
#### ĐỘ LỆCH CHUẨN là căn bậc hai của phương sai. Nó cũng đo mức độ phân tán, nhưng có cùng đơn vị với các giá trị ban đầu trong tập dữ liệu, do đó dễ hiểu và sử dụng hơn phương sai..

![Công thức phương sai](dolechchuan.png)
![Công thức độ lệch chuẩn](1.png)
![Ví dụ](2.png)




In [93]:
dog_height = [600,470,170,430,300] # chiều cao của 5 con chó, với giá trị mean ( trung bình ) là : 394 
dog_height = np.array(dog_height)
np.std(dog_height) 
# tính độ lệch chuẩn, ta có độ lệch chuẩn là 147. Vậy có nghĩa là những con chó cao trong khoảng 394 +- 147 là những con chó cao trung bình

147.32277488562318

In [94]:
np.var(dog_height)

21704.0

# Sorting arrays 
np.sort dữ trên thuật toán quick sort 

In [95]:
x = np.array([2,1,3,4,5])
np.sort(x)

array([1, 2, 3, 4, 5])

In [97]:
np.argsort(x) # trả về VỊ TRÍ của các index, ví dụ số 1 nằm ở vị trí số 1, số 2 nằm ở vị trí 0 

array([1, 0, 2, 3, 4], dtype=int64)

# Sorting qua dòng và cột 

In [98]:
np.random.seed(42) 
MatA = np.random.randint(0,10, size =(4,6))

In [99]:
MatA

array([[6, 3, 7, 4, 6, 9],
       [2, 6, 7, 4, 3, 7],
       [7, 2, 5, 4, 1, 7],
       [5, 1, 4, 0, 9, 5]])

In [100]:
np.sort(MatA, axis = 0) # Sắp xếp theo cột 

array([[2, 1, 4, 0, 1, 5],
       [5, 2, 5, 4, 3, 7],
       [6, 3, 7, 4, 6, 7],
       [7, 6, 7, 4, 9, 9]])

In [101]:
np.sort(MatA, axis = 1) # Sắp xếp theo hàng 

array([[3, 4, 6, 6, 7, 9],
       [2, 3, 4, 6, 7, 7],
       [1, 2, 4, 5, 7, 7],
       [0, 1, 4, 5, 5, 9]])

 # Đại số tuyến tính 

In [108]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [109]:
b = np.array([[6,5],[4,3],[2,1]])
b

array([[6, 5],
       [4, 3],
       [2, 1]])

In [107]:
# a(3x3) nhân b (3x2) => nhân đc vì cột a = hàng b 
a.dot(b) # a nhân tích vô hướng với ma trận b 


array([[20, 14],
       [56, 41],
       [92, 68]])

In [110]:
1*6 + 2*4 + 3*2 

20

In [111]:
a @ b 

array([[20, 14],
       [56, 41],
       [92, 68]])

In [115]:
# b(3x2) nhân vô hướng a (3x3) => k nhân đc vì cột b != hàng a, nhưng ta có thể transpose b để nhân 
c= b.T # (2x3) dot a(3x3) 

In [116]:
c @ a 

array([[36, 48, 60],
       [24, 33, 42]])

# Ví dụ sử dụng numpy + pandas 

In [120]:
np.random.seed(0)
sales_amount = np.random.randint(20, size =(5,3))
sales_amount

array([[12, 15,  0],
       [ 3,  3,  7],
       [ 9, 19, 18],
       [ 4,  6, 12],
       [ 1,  6,  7]])

In [124]:
import pandas as pd 
weekly_sales = pd.DataFrame(sales_amount, index = ["Mon","Tues","Wed","Thurs","Fri"], columns = ["apples","bananas","oranges"])
weekly_sales 

apples  bananas  oranges
Mon        12       15        0
Tues        3        3        7
Wed         9       19       18
Thurs       4        6       12
Fri         1        6        7

In [125]:
prices = np.array([10,8,11]) 
#create a price array 

In [128]:
prices.shape

(3,)

In [129]:
products_price = pd.DataFrame(prices.reshape(1,3), index =["Price"], columns = ["apples","bananas","oranges"]) 

In [130]:
products_price

apples  bananas  oranges
Price      10        8       11

### Tính tổng doanh thu trong 1 tuần 

In [134]:
products_price.shape, weekly_sales.shape 

((1, 3), (5, 3))

In [135]:
price_of_products = products_price.T 

In [136]:
total_prices = weekly_sales.dot(price_of_products)

In [137]:
total_prices 

Price
Mon      240
Tues     131
Wed      440
Thurs    220
Fri      135

#### Thêm cột "Total_prices" vào trong dataframe 

In [138]:
weekly_sales["Total_price"] = total_prices 
weekly_sales 

apples  bananas  oranges  Total_price
Mon        12       15        0          240
Tues        3        3        7          131
Wed         9       19       18          440
Thurs       4        6       12          220
Fri         1        6        7          135